version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: swc-postgres
    restart: always
    environment:
      POSTGRES_USER: swc_user
      POSTGRES_PASSWORD: swc_password
      POSTGRES_DB: swc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: swc-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@swc.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
